# 配置服务端口号
server:
  port: 10200

# 配置数据库的连接信息
spring:
  application:
    name: cloud-order
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
            read-timeout: 2000
            connect-timeout: 2000
            retryer: com.atguigu.cloud.order.feign.FeignClientRetryer
    nacos:
      discovery:
        server-addr: 10.211.55.10:8848
        cluster-name: SH
        weight: 1
        namespace: ba640a5a-e8be-47cd-be38-6f9e48551ac8
    loadbalancer:
      nacos:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.10:3306/cloud-order
    username: root
    password: root

# 配置mybatis-plus的相关信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.atguigu.cloud.order.feign: debug
