server:
  port: 8222
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cloud-user  # 路由id，可以自定义，只要唯一即可
          uri: lb://cloud-user  # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/*/user/** # 路径匹配
        - id: cloud-order
          uri: lb://cloud-order
          predicates:
            - Path=/*/order/** # 路径匹配

    nacos: #注意和其他微服务的名称空间保持一致
      discovery:
        server-addr: 10.211.55.10:8848
        username: nacos
        password: nacos
        namespace: ba640a5a-e8be-47cd-be38-6f9e48551ac8